import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import { format, resolveConfig } from 'prettier';

const spec = resolve('../../apps/api/openapi.json');
const output = resolve('src/schema.ts');
const schema = JSON.parse(await readFile(spec, 'utf8'));
const nodes = await openapiTS(schema);
const generated =
  '/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n' +
  astToString(nodes);
await writeFile(
  output,
  await format(generated, { ...(await resolveConfig(output)), filepath: output }),
);
