/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/google/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['startGoogleSignIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['finishGoogleSignIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAuthSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/session/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['refreshAuthSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['logoutCurrentSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['logoutAllSessions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listAuthSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['revokeAuthSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/phone': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['updatePhoneNumber'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getLiveHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getReadyHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    GoogleStartDto: {
      /** @enum {string} */
      returnTo: '/app' | '/onboarding/phone' | '/settings/sessions';
    };
    GoogleStartResponseDto: {
      /** Format: uri */
      authorizationUrl: string;
      transactionToken: string;
      /** Format: date-time */
      expiresAt: string;
    };
    GoogleCallbackDto: {
      code?: string;
      state: string;
      transactionToken: string;
      providerError?: string;
    };
    AuthUserDto: {
      id: string;
      displayName: string;
      avatarUrl?: string | null;
      /** @enum {string} */
      phoneStatus: 'NONE' | 'UNVERIFIED' | 'VERIFIED';
      maskedPhone?: string | null;
    };
    DeviceSummaryDto: {
      browser: string;
      operatingSystem: string;
      /** @enum {string} */
      deviceType: 'DESKTOP' | 'MOBILE' | 'TABLET' | 'UNKNOWN';
    };
    CurrentSessionDto: {
      id: string;
      /** @enum {boolean} */
      current: true;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastSeenAt: string;
      /** Format: date-time */
      accessExpiresAt: string;
      /** Format: date-time */
      absoluteExpiresAt: string;
      device: components['schemas']['DeviceSummaryDto'];
    };
    OnboardingDto: {
      /** @enum {string} */
      nextAction: 'PHONE_REQUIRED' | 'PHONE_VERIFICATION_REQUIRED' | 'NONE';
    };
    AuthSessionResponseDto: {
      /** @enum {boolean} */
      authenticated: true;
      csrfToken: string;
      user: components['schemas']['AuthUserDto'];
      session: components['schemas']['CurrentSessionDto'];
      onboarding: components['schemas']['OnboardingDto'];
    };
    TokenSessionResponseDto: {
      accessToken: string;
      refreshToken: string;
      /** Format: date-time */
      accessExpiresAt: string;
      /** Format: date-time */
      refreshExpiresAt: string;
      session: components['schemas']['AuthSessionResponseDto'];
      returnTo?: string;
    };
    RefreshSessionDto: {
      refreshToken: string;
    };
    LogoutDto: {
      accessToken?: string;
      refreshToken?: string;
    };
    DeviceSessionResponseDto: {
      id: string;
      current: boolean;
      device: components['schemas']['DeviceSummaryDto'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastSeenAt: string;
      /** Format: date-time */
      absoluteExpiresAt: string;
    };
    RevokeSessionResponseDto: {
      revokedCurrent: boolean;
    };
    UpdatePhoneDto: {
      /** @example +84901234567 */
      phone: string;
    };
    HealthResponseDto: {
      /** @enum {string} */
      status: 'ok' | 'unavailable';
      /** Format: uuid */
      requestId: string;
      dependencies?: {
        [key: string]: {
          /** @enum {string} */
          status: 'up' | 'down';
        };
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  startGoogleSignIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleStartDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GoogleStartResponseDto'];
        };
      };
    };
  };
  finishGoogleSignIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleCallbackDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenSessionResponseDto'];
        };
      };
    };
  };
  getAuthSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSessionResponseDto'];
        };
      };
    };
  };
  refreshAuthSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshSessionDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenSessionResponseDto'];
        };
      };
    };
  };
  logoutCurrentSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logoutAllSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAuthSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeviceSessionResponseDto'][];
        };
      };
    };
  };
  revokeAuthSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RevokeSessionResponseDto'];
        };
      };
    };
  };
  updatePhoneNumber: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePhoneDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSessionResponseDto'];
        };
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSessionResponseDto'];
        };
      };
    };
  };
  getLiveHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
  getReadyHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
}
